import { TranslationDictionary } from './types';

export const en: TranslationDictionary = {
  intro: {
    continueInvestigation: 'CONTINUE INVESTIGATION',
    startNewInvestigation: 'START NEW INVESTIGATION',
    aboutGame: 'About the game',
    settings: 'Settings',
    gameTitle: 'The Secret of the',
    gameTitleSub: 'Silent Lake',
    cabinMystery: 'MURDER MYSTERY AT THE CABIN',
    quote: '"The cabin was silent. Too silent."',
    startInvestigation: 'START INVESTIGATION',
    startNew: 'Start a new investigation',
    confirmNewGame: 'Start a new game?',
    confirmNewGameDesc: 'This will delete your current progress saved in your browser and start the murder investigation from the very beginning. This action cannot be undone.',
    cancel: 'Cancel',
    confirmReset: 'Yes, start over',
    aboutTitle: 'About the Game & Instructions',
    aboutParagraph1: 'Six friends gather to spend a weekend at a remote lakeside cabin in Finland. In the evening, a member of the group, Antti Lehtonen, disappears under mysterious circumstances. The next morning, he is found dead near the boathouse.',
    aboutParagraph2: 'A storm has cut the power and blocked the only access road, preventing the police from reaching the scene quickly. As a detective, you must take charge of the situation.',
    aboutParagraph3: 'Your mission: Investigate locations on the map, find 20 hidden clues, interrogate five suspects, and reveal who among them is the killer, what the motive was, where the murder took place, and what the murder weapon was.',
    howToPlay: 'How to Play:',
    rule1: 'Investigate locations on the map by clicking on objects to find clues.',
    rule2: 'Interrogate suspects. Discovered clues unlock new questions.',
    rule3: 'Combine evidence and suspect alibis on the investigation board to find contradictions.',
    rule4: 'When you are ready, make an official accusation in the accusation view.',
    backToMenu: 'Back to Main Menu',
  },
  navigation: {
    map: 'Map',
    evidence: 'Evidence',
    suspects: 'Suspects',
    board: 'Investigation Board',
    notes: 'Notes',
    settings: 'Settings',
    returnToMap: 'Return to Map',
  },
  settings: {
    language: 'Language',
    finnish: 'Suomi',
    english: 'English',
    title: 'Game Settings',
    sounds: 'Sounds & Effects',
    music: 'Ambient Music',
    sfx: 'Sound Effects',
    on: 'ON',
    off: 'OFF',
    audioDisclaimer: '* Background ambient sounds are synthesized dynamically in your browser (rain and wind without loading times).',
    textSizeTitle: 'UI & Text Size',
    textSizeNormal: 'Normal',
    textSizeLarge: 'Large',
    textSizeHuge: 'Huge',
    accessibility: 'Accessibility & Display',
    reducedMotion: 'Reduced Motion',
    reducedMotionDesc: 'Useful for sensitive eyes or older devices.',
    fullscreen: 'Fullscreen Mode',
    fullscreenDesc: 'Expand game to full screen (if browser and iframe allow).',
    returnToMainMenu: 'Return to Main Menu',
    done: 'Done',
  },
  investigation: {
    examine: 'Examine',
    discovered: 'Discovered',
    newEvidence: 'New Evidence',
    evidenceAdded: 'Evidence Added',
    interrogate: 'Interrogate',
    accuse: 'Accuse',
    confirmAccusation: 'Confirm Accusation',
    cancel: 'Cancel',
    close: 'Close',
    continue: 'Continue',
    notesPlaceholder: 'Write your own notes here... They will be saved automatically.',
    cluesFound: 'Discovered Clues',
    noCluesYet: "You haven't found any clues yet. Explore different locations on the map.",
    caseFiles: 'Case Files',
    selectClueToAnalyze: 'Select a clue from the left to view detailed laboratory results and forensic observations.',
    category: 'Category',
    forensicReport: 'Forensic Analysis',
    investigativeSignificance: 'Investigative Significance',
    location: 'Location',
    foundIn: 'Found In',
    misleadingEvidence: 'Misleading Evidence',
    vitalClue: 'Vital Clue',
    suspectsTitle: 'Interrogation Room',
    selectSuspect: 'Select a suspect to interrogate. Each of them has their own secrets and potential motives.',
    age: 'Age',
    role: 'Role',
    motive: 'Motive',
    alibi: 'Alibi',
    dialogueTopics: 'Interrogation Questions',
    noTopics: 'No new questions available. Find more clues to unlock new topics.',
    boardTitle: 'Investigation Board & Contradictions',
    boardSubtitle: 'Combine clues, interrogation responses, or alibis by dragging them onto each other to find contradictions in the suspects\' statements.',
    contradictionsDiscovered: 'Discovered Contradictions',
    noContradictionsYet: "You haven't found any contradictions yet. Try combining evidence or interrogation statements.",
    contradictionTitle: 'New Contradiction Revealed!',
  },
  board: {
    title: 'Cabin Area Investigation Board',
    subtitle: 'Place discovered evidence and suspects\' official alibis on the cork board. Connect any two items to see if they reveal contradictions or confirm statements.',
    connectorTitle: 'Deductive Connector (Select two different items)',
    resetSelection: 'Reset selections',
    misleading: 'Misleading',
    evidence: 'Evidence',
    evidenceCategory: 'Evidence',
    alibiCategory: 'Alibi',
    noContradictionMessage: 'No direct contradiction. These two things do not negate each other or form a significant new conclusion. Review the details of your evidence again.',
    connectBtn: 'CONNECT EVIDENCE',
    connectedTitle: 'Connected Items',
    emptySlot: 'Empty Slot',
    emptySlotDesc: 'Select an item below to fill',
    contradictionDiscovered: 'CONTRADICTION DISCOVERED!',
    viewContradictions: 'Discovered Contradictions ({count}/7)',
    contradictionDesc: 'Resolved contradictions on the investigation board that advance the case.',
    allFound: 'All 7 contradictions found! Watertight case compiled.',
    uncoveredItemA: 'Evidence A',
    uncoveredItemB: 'Evidence B',
    explanation: 'Explanation',
    alibiLabel: 'Alibi',
    physicalEvidenceGroup: 'Physical Evidence',
    documentsGroup: 'Documents',
    personRelatedGroup: 'Person-related',
    unknownClue: 'Unknown Evidence',
    clueShorthand: 'EVIDENCE',
    foundIn: 'Found in',
    whyImportant: 'Why it is important',
    relatedSuspect: 'Related suspect',
    clueNumber: 'Evidence #{number}',
    closeBtn: 'Close',
    corkboardTitle: 'Detective Corkboard',
    corkboardSubtitle: 'Investigator workspace with discovered evidence grouped. Click a card to inspect it in detail.',
    analysisLabel: 'Forensic analysis',
    categoryLabel: 'Category',
    evidenceValueLabel: 'Evidence Value',
  },
  accusation: {
    title: 'Making an Accusation',
    subtitle: 'As a detective, you bear the responsibility to point out the killer and prove guilt beyond doubt. Select the suspect, motive, location, murder weapon, and three vital pieces of evidence to support the accusation.',
    killer: 'The Killer',
    motive: 'Motive',
    weapon: 'Murder Weapon',
    location: 'Crime Scene',
    evidence: 'Evidence (select exactly 3)',
    submit: 'SUBMIT OFFICIAL ACCUSATION',
    invalid: 'Fill in all fields and select exactly 3 pieces of evidence before submitting the accusation.',
    failedTitle: 'Accusation Dismissed',
    failedDesc: 'The accusation you submitted is not convincing enough or some elements are incorrect. Study the evidence more carefully and try again.',
    backToInvestigation: 'Continue Investigation',
  },
  ending: {
    title: 'Investigation Concluded',
    correctTitle: 'Correct Accusation! Case Solved.',
    attempts: 'Solved in {attempts} attempt(s).',
    congratulations: 'Congratulations, you have solved the secret of the Silent Lake!',
    mainMenu: 'Return to Main Menu',
  },
  general: {
    loading: 'Loading...',
    error: 'Error',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    yearsOld: 'years old',
    progress: 'Progress',
    sound: 'Sound',
    effects: 'Effects',
    muteSounds: 'Mute background sounds',
    unmuteSounds: 'Enable background sounds',
    muteEffects: 'Mute sound effects',
    unmuteEffects: 'Enable sound effects',
    settings: 'Settings',
    phases: {
      prologue: 'Prologue',
      phase1: 'Phase 1: Initial Investigation',
      phase2: 'Phase 2: Secrets',
      phase3: 'Phase 3: Evidence',
      accusation: 'Accusation Phase',
      ending: 'Resolution',
      ongoing: 'Investigation in progress',
    }
  }
};
