import { TranslationDictionary } from './types';

export const fi: TranslationDictionary = {
  intro: {
    continueInvestigation: 'JATKA TUTKINTAA',
    startNewInvestigation: 'ALOITA UUSI TUTKINTA',
    aboutGame: 'Tietoa pelistä',
    settings: 'Asetukset',
    gameTitle: 'Hiljaisen järven',
    gameTitleSub: 'salaisuus',
    cabinMystery: 'MURHAMYSTEERI MÖKILLÄ',
    quote: '"Mökki oli hiljainen. Liian hiljainen."',
    startInvestigation: 'ALOITA TUTKINTA',
    startNew: 'Aloita uusi tutkinta',
    confirmNewGame: 'Aloitetaanko uusi peli?',
    confirmNewGameDesc: 'Tämä poistaa selaimeesi tallennetun nykyisen edistymisesi ja aloittaa murhatutkinnan kokonaan alusta. Tätä toimintoa ei voi peruuttaa.',
    cancel: 'Peruuta',
    confirmReset: 'Kyllä, aloita alusta',
    aboutTitle: 'Pelin tausta & ohjeet',
    aboutParagraph1: 'Kuusi ystävää kokoontuu viettämään viikonloppua syrjäiselle järvenrantamökille Suomessa. Illalla ryhmän jäsen Antti Lehtonen katoaa hämärissä olosuhteissa. Seuraavana aamuna hänet löydetään kuolleena venevajan läheltä.',
    aboutParagraph2: 'Myrsky on katkaissut sähköt ja tukkinut ainoan ajotien, joten poliisi ei pääse paikalle nopeasti. Rikostutkijana sinun täytyy ottaa vastuu tilanteesta.',
    aboutParagraph3: 'Tehtäväsi: Tutki paikkoja kartalta, löydä 20 piilotettua johtolankaa, kuulustele viittä epäiltyä ja paljasta kuka heistä on murhaaja, mikä oli motiivi, missä murha tehtiin ja mikä oli murha-ase.',
    howToPlay: 'Kuinka pelata:',
    rule1: 'Tutki paikkoja kartalta klikkaamalla kohteita löytääksesi johtolankoja.',
    rule2: 'Kuulustele epäiltyjä. Löydetyt johtolangat avaavat uusia kysymyksiä.',
    rule3: 'Yhdistä todisteita ja epäiltyjen alibeja tutkintataululla löytääksesi ristiriitoja.',
    rule4: 'Kun olet valmis, tee virallinen syytös syytösnäkymässä.',
    backToMenu: 'Takaisin päävalikkoon',
  },
  navigation: {
    map: 'Kartta',
    evidence: 'Johtolangat',
    suspects: 'Epäillyt',
    board: 'Tutkintataulu',
    notes: 'Muistiinpanot',
    settings: 'Asetukset',
    returnToMap: 'Palaa kartalle',
  },
  settings: {
    language: 'Kieli',
    finnish: 'Suomi',
    english: 'English',
    title: 'Peliasetukset',
    sounds: 'Äänet & Tehosteet',
    music: 'Taustaäänet',
    sfx: 'Ääniefektit',
    on: 'PÄÄLLÄ',
    off: 'POIS',
    audioDisclaimer: '* Taustaäänet syntetisoidaan dynaamisesti selaimessasi (sadetta ja tuulta ilman latausaikoja).',
    textSizeTitle: 'Käyttöliittymä & Tekstin koko',
    textSizeNormal: 'Normaali',
    textSizeLarge: 'Suuri',
    textSizeHuge: 'Erittäin suuri',
    accessibility: 'Saavutettavuus & Näyttö',
    reducedMotion: 'Vähennä animaatioita',
    reducedMotionDesc: 'Hyödyllinen herkemmille silmille tai vanhemmille laitteille.',
    fullscreen: 'Koko näytön tila',
    fullscreenDesc: 'Laajenna peli koko näytölle (jos selaimesi ja iframe sallivat).',
    returnToMainMenu: 'Palaa päävalikkoon',
    done: 'Valmis',
  },
  investigation: {
    examine: 'Tutki',
    discovered: 'Löydetty',
    newEvidence: 'Uusi johtolanka',
    evidenceAdded: 'Johtolanka lisätty',
    interrogate: 'Kuulustele',
    accuse: 'Syytä',
    confirmAccusation: 'Vahvista syytös',
    cancel: 'Peruuta',
    close: 'Sulje',
    continue: 'Jatka',
    notesPlaceholder: 'Kirjoita omia muistiinpanojasi tähän... Ne tallentuvat automaattisesti.',
    cluesFound: 'Löydetyt johtolangat',
    noCluesYet: 'Et ole vielä löytänyt yhtään johtolankaa. Tutki eri kohteita kartalla.',
    caseFiles: 'Tutkinta-aineisto',
    selectClueToAnalyze: 'Valitse johtolanka vasemmalta nähdäksesi yksityiskohtaiset laboratoriotulokset ja rikostekniset havainnot.',
    category: 'Kategoria',
    forensicReport: 'Rikostekninen analyysi',
    investigativeSignificance: 'Tutkinnallinen merkitys',
    location: 'Sijainti',
    foundIn: 'Löytöpaikka',
    misleadingEvidence: 'Harhaanjohtava todiste',
    vitalClue: 'Keskeinen todiste',
    suspectsTitle: 'Kuulusteluhuone',
    selectSuspect: 'Valitse epäilty kuulusteltavaksi. Jokaisella heistä on omat salaisuutensa ja mahdolliset motiivinsa.',
    age: 'Ikä',
    role: 'Asema',
    motive: 'Motiivi',
    alibi: 'Alibi',
    dialogueTopics: 'Kuulustelukysymykset',
    noTopics: 'Ei uusia kysymyksiä saatavilla. Etsi lisää johtolankoja avataksesi uusia aiheita.',
    boardTitle: 'Tutkintataulu & Ristiriidat',
    boardSubtitle: 'Yhdistä johtolankoja, kuulusteluvastauksia tai alibeja vetämällä niitä toistensa päälle löytääksesi ristiriitoja epäiltyjen puheissa.',
    contradictionsDiscovered: 'Löydetyt ristiriidat',
    noContradictionsYet: 'Et ole vielä löytänyt yhtään ristiriitaa. Kokeile yhdistellä todisteita tai kuulustelukertomuksia.',
    contradictionTitle: 'Uusi ristiriita paljastettu!',
  },
  board: {
    title: 'Mökkialueen Tutkintataulu',
    subtitle: 'Aseta löytämiäsi todisteita ja epäiltyjen virallisia alibeja korkkitaululle. Yhdistä kaksi asiaa ja katso, paljastavatko ne ristiriitaisuuksia tai vahvistavatko ne kertomuksia.',
    connectorTitle: 'Deduktiivinen yhdistäjä (Valitse kaksi erilaista kohdetta)',
    resetSelection: 'Nollaa valinnat',
    misleading: 'Harhautus',
    evidence: 'Todiste',
    evidenceCategory: 'Johtolanka',
    alibiCategory: 'Alibi',
    noContradictionMessage: 'Ei suoraa ristiriitaa. Nämä kaksi asiaa eivät kumoa toisiaan tai muodosta merkittävää uutta päätelmää. Tarkastele johtolankojen yksityiskohtia uudelleen.',
    connectBtn: 'YHDISTÄ TODISTEET',
    connectedTitle: 'Yhdistetyt kohteet',
    emptySlot: 'Tyhjä paikka',
    emptySlotDesc: 'Valitse alta kohde täyttääksesi',
    contradictionDiscovered: 'RISTIRIITA PALJASTETTU!',
    viewContradictions: 'Löydetyt Ristiriidat ({count}/7)',
    contradictionDesc: 'Tutkintataululla ratkaistut ristiriidat, jotka vievät tutkimusta eteenpäin.',
    allFound: 'Kaikki 7 ristiriitaa löydetty! Vedenpitävä näyttö kasassa.',
    uncoveredItemA: 'Todiste A',
    uncoveredItemB: 'Todiste B',
    explanation: 'Selitys',
    alibiLabel: 'Alibi',
    physicalEvidenceGroup: 'Fyysiset todisteet',
    documentsGroup: 'Asiakirjat',
    personRelatedGroup: 'Henkilöihin liittyvät',
    unknownClue: 'Tuntematon todiste',
    clueShorthand: 'TODISTE',
    foundIn: 'Löytöpaikka',
    whyImportant: 'Miksi se on tärkeä',
    relatedSuspect: 'Liittyy epäiltyyn',
    clueNumber: 'Todiste #{number}',
    closeBtn: 'Sulje',
    corkboardTitle: 'Rikostutkinnan Korkkitaulu',
    corkboardSubtitle: 'Tutkijan työtila ja löydetyt todisteet ryhmiteltynä. Klikkaa korttia tarkastellaksesi sitä.',
    analysisLabel: 'Tutkijan analyysi',
    categoryLabel: 'Kategoria',
    evidenceValueLabel: 'Todistusarvo',
  },
  accusation: {
    title: 'Syytöksen tekeminen',
    subtitle: 'Rikostutkijana sinulla on vastuu osoittaa murhaaja ja todistaa syyllisyys vedenpitävästi. Valitse epäilty, motiivi, tekopaikka, murha-ase sekä kolme keskeistä todistetta syytöksen tueksi.',
    killer: 'Syyllinen',
    motive: 'Motiivi',
    weapon: 'Murha-ase',
    location: 'Tekopaikka',
    evidence: 'Todisteet (valitse tasan 3)',
    submit: 'ESITÄ VIRALLINEN SYYTÖS',
    invalid: 'Täytä kaikki kohdat ja valitse tasan 3 todistetta ennen syytöksen esittämistä.',
    failedTitle: 'Syytös hylätty',
    failedDesc: 'Esittämäsi syytös ei ole riittävän vakuuttava tai jokin sen osatekijöistä on virheellinen. Tutki todisteita tarkemmin ja kokeile uudelleen.',
    backToInvestigation: 'Jatka tutkintaa',
  },
  ending: {
    title: 'Tutkinta Päätetty',
    correctTitle: 'Oikea Syytös! Tapaus ratkaistu.',
    attempts: 'Ratkaistu {attempts} yrityksellä.',
    congratulations: 'Onnittelut, olet ratkaissut Hiljaisen järven salaisuuden!',
    mainMenu: 'Palaa päävalikkoon',
  },
  general: {
    loading: 'Ladataan...',
    error: 'Virhe',
    ok: 'OK',
    yes: 'Kyllä',
    no: 'Ei',
    back: 'Takaisin',
    yearsOld: 'vuotta',
    progress: 'Eteneminen',
    sound: 'Äänet',
    effects: 'Efektit',
    muteSounds: 'Mykistä taustaäänet',
    unmuteSounds: 'Ota taustaäänet käyttöön',
    muteEffects: 'Mykistä tehosteet',
    unmuteEffects: 'Ota tehosteet käyttöön',
    settings: 'Asetukset',
    phases: {
      prologue: 'Prologi',
      phase1: 'Vaihe 1: Alkututkinta',
      phase2: 'Vaihe 2: Salaisuudet',
      phase3: 'Vaihe 3: Todisteet',
      accusation: 'Syytösvaihe',
      ending: 'Loppuratkaisu',
      ongoing: 'Tutkinta käynnissä',
    }
  }
};
